---
enable_debug: false

##
# vars from inventory
cs_portal_domain: ""
consul_listen_ip: "127.0.0.1"

##
# Agent Configuration
agent_sentry_dsn: "https://491b61104d5f43789787a33d97cc140e@o479519.ingest.sentry.io/5524586"
docker_api_version: "1.40"
agent_image: "cmptstks/borg:stable"
agent_download_url: "https://cdn.computestacks.net/packages/cs-agent/cs-agent.tar.gz"

# Paths
agent_config_path: /etc/computestacks
agent_certs_dir: "{{ agent_config_path }}/certs"
agent_docker_certs_dir: "{{ agent_certs_dir }}/docker"
agent_consul_certs_dir: "{{ agent_certs_dir }}/consul"

# Backup Configuration
backups_enabled: true
backups_destination: "/mnt/backups"
backups_check_freq: "*/2 * * * *"
backups_prune_freq: "15 1 * * *"
backups_key: "changme!"