---
- name: default nginx conf
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: computestacks nginx conf
  template:
    src: computestacks.conf
    dest: /etc/nginx/conf.d/computestacks.conf
  when: "'controller' in group_names"

- name: loki vhost conf
  template:
    src: loki.conf
    dest: /etc/nginx/conf.d/loki.conf
  when: "'metrics' in group_names"

- name: prometheus vhost conf
  template:
    src: prometheus.conf
    dest: /etc/nginx/conf.d/prometheus.conf
  when: "'metrics' in group_names"

- name: loki nginx password
  community.general.htpasswd:
    path: /etc/nginx/passwords/loki.htpasswd
    name: "{{ loki_username }}"
    password: "{{ loki_password }}"
  when: "'metrics' in group_names"

- name: prometheus nginx password
  community.general.htpasswd:
    path: /etc/nginx/passwords/prometheus.htpasswd
    name: "{{ prometheus_username }}"
    password: "{{ prometheus_password }}"
  when: "'metrics' in group_names"
