---
- include_tasks: preflight.yml

- name: Check if Acme initialized
  stat:
    path: "{{ nginx_cert_fullchain }}"
  register: le_initialized

- include_tasks: acme.yml
  when: le_initialized.stat.exists == False

- include_tasks: finalize.yml

- name: start nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
