---
- name: add pg key
  ansible.builtin.apt_key:
    url: "{{ psql_deb_key }}"
    state: present

- name: add pg repo
  ansible.builtin.apt_repository:
    repo: "{{ psql_deb_repo_url }}"
    state: present
    filename: postgresql
  
- name: install packages
  apt:
    name:
      - "postgresql-{{ psql_version }}"
      - "postgresql-{{ psql_version }}-ip4r"
      - python3-psycopg2
    state: present
    update_cache: yes
