- name: install
  yum:
    name: haproxy22
    state: present

- name: create certificate directory
  file:
    path: /etc/haproxy/certs
    state: directory

- name: install default error page
  copy:
    src: default.http
    dest: '/etc/haproxy/default.http'

- name: stats directory
  file:
    path: /run/haproxy
    state: directory
    owner: haproxy
    group: haproxy

- name: persist stats
  copy:
    src: haproxy.conf
    dest: /usr/lib/tmpfiles.d/haproxy.conf

- name: create lib
  file:
    path: /var/lib/haproxy
    state: directory
    owner: haproxy
    group: haproxy

- name: selinux (haproxy_connect_any)
  shell: setsebool -P haproxy_connect_any 1
  vars:
    ansible_ssh_pipelining: no

- name: selinux (cluster_use_execmem)
  shell: setsebool -P cluster_use_execmem 1
  vars:
    ansible_ssh_pipelining: no

# Ensure that centos nodes have same structure as debian/ubuntu
- name: copy error files
  shell: rsync -a /usr/share/haproxy/ /etc/haproxy/errors/
  vars:
    ansible_ssh_pipelining: no

- name: start
  service:
    name: haproxy
    state: started
    enabled: yes
