---
- include_tasks: debian/install.yml

- name: create certificate directory
  file:
    path: /etc/haproxy/certs
    state: directory

- name: install default error page
  copy:
    src: default.http
    dest: '/etc/haproxy/default.http'

- name: start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
