---
- name: "Check if docker already enabled"
  shell: "{{ vault_command }} secrets list | grep docker"
  register: vault_docker_enabled
  failed_when: vault_docker_enabled.rc > 1

- block:
    - name: Setup docker pki mount
      command: "{{ vault_command }} secrets enable -path=pki/docker pki"
      register: enable_docker_pki
    - name: Tune docker TTL
      command: "{{ vault_command }} secrets tune -max-lease-ttl=87600h pki/docker"
    - name: Generate docker CA
      command: |
        {{ vault_command }} write -field certificate pki/docker/root/generate/internal common_name="Docker Root CA" ttl=87600h
      register: vault_docker_ca
    - name: Write docker CA to file
      copy:
        content: "{{ vault_docker_ca.stdout }}\n"
        dest: "{{ docker_certs_path }}/ca.pem"
    - name: Setup docker daemon role
      command: |
        {{ vault_command }} write pki/docker/roles/server \
                                              max_ttl=87600h \
                                              ttl=8760h  \
                                              allow_any_name=true \
                                              allow_localhost=true \
                                              allow_ip_sans=true \
                                              allow_bare_domains=true \
                                              allow_subdomains=true \
                                              server_flag=true \
                                              client_flag=false \
                                              key_usage=DigitalSignature,KeyEncipherment \
                                              ou="Docker Daemon"
    - name: Setup docker client role
      command: |
        {{ vault_command }} write pki/docker/roles/client \
                                              max_ttl=87600h \
                                              ttl=720h  \
                                              allow_any_name=true \
                                              enforce_hostnames=false \
                                              server_flag=false \
                                              client_flag=true \
                                              key_usage=DigitalSignature \
                                              ou="Docker Client" \
                                              no_store=true
    - name: Generate ComputeStacks docker certificate
      command: |
        {{ vault_command }} write -format json pki/docker/issue/client \
                                                    common_name=portal \
                                                    ttl=43800h
      register: vault_docker_client_results
    - name: Parse output of vault client generate
      set_fact:
        vault_client_parsed: "{{ vault_docker_client_results.stdout | from_json }}"
    - name: Write client cert
      copy:
        content: "{{ vault_client_parsed.data.certificate }}\n"
        dest: "{{ docker_certs_path }}/cert.pem"
    - name: Write ca cert
      copy:
        content: "{{ vault_client_parsed.data.issuing_ca }}\n"
        dest: "{{ docker_certs_path }}/ca.pem"
    - name: Write client key
      copy:
        content: "{{ vault_client_parsed.data.private_key }}\n"
        dest: "{{ docker_certs_path }}/key.pem"
    - name: Build client pem
      shell: |
        cat {{ docker_certs_path }}/cert.pem {{ docker_certs_path }}/ca.pem {{ docker_certs_path }}/key.pem > {{ docker_certs_path }}/client.pem
  when: vault_docker_enabled.rc == 1