---
- name: "Check if etcd already enabled"
  shell: "{{ vault_command }} secrets list | grep etcd"
  register: vault_etcd_enabled
  failed_when: vault_etcd_enabled.rc > 1

- block:
    - name: Setup etcd pki
      command: |
        {{ vault_command }} secrets enable -path=pki/etcd pki
    - name: Tune etcd TTL
      command: |
        {{ vault_command }} secrets tune -max-lease-ttl=87600h pki/etcd
    - name: Generate etcd CA
      command: |
        {{ vault_command }} write -field certificate pki/etcd/root/generate/internal common_name="etcd Root CA" ttl=87600h
    - name: Setup etcd server role
      command: |
        {{ vault_command }} write pki/etcd/roles/server \
                                    max_ttl=87600h \
                                    ttl=8760h  \
                                    allow_any_name=true \
                                    allow_localhost=true \
                                    allow_ip_sans=true \
                                    allow_bare_domains=true \
                                    allow_subdomains=true \
                                    server_flag=true \
                                    client_flag=true \
                                    key_usage=DigitalSignature,KeyEncipherment \
                                    ou="etcd daemon"
    - name: Setup etcd client role
      command: |
        {{ vault_command }} write pki/etcd/roles/client \
                                    max_ttl=87600h \
                                    ttl=720h  \
                                    allow_any_name=true \
                                    enforce_hostnames=false \
                                    server_flag=false \
                                    client_flag=true \
                                    key_usage=DigitalSignature \
                                    ou="etcd client" \
                                    no_store=true
  when: vault_etcd_enabled.rc == 1
