---
- name: collect and register consul token
  uri:
    url: "http://{{ consul_listen_ip }}:8500/v1/acl/bootstrap"
    method: PUT
    return_content: yes
    status_code: 200
    body_format: json
  register: consul_token_raw

- set_fact:
    consul_token: "{{ consul_token_raw['json']['SecretID'] }}"

- name: store token
  template:
    src: consul-secret
    dest: /root/.consul.secret
    mode: 0600
    owner: root
    group: root

# curl -X PUT -H "X-Consul-Token: $CONSUL_HTTP_TOKEN" -H "Content-Type: application/json" --data "{\"Token\": \"$CONSUL_HTTP_TOKEN\"}" http://localhost:8500/v1/agent/token/default
- name: set default consul token
  uri:
    url: "http://{{ consul_listen_ip }}:8500/v1/agent/token/default"
    method: PUT
    body_format: json
    headers:
      Content-Type: application/json
      X-Consul-Token: "{{ consul_token }}"
    body:
      Token: "{{ consul_token }}"
