---
- name: Generate consul certificate directory
  file:
    path: "{{ consul_ssl_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Request consul server certificate
  shell: |
    docker exec -it vault-bootstrap vault write -format json pki/consul/issue/server \
                                                common_name={{ hostvars[inventory_hostname].ansible_hostname }} \
                                                alt_names=localhost \
                                                ip_sans="127.0.0.1,{{ consul_listen_ip }}" \
                                                ttl=43800h
  register: consul_server_cert
  delegate_to: "{{ groups['controller'][0] }}"
  vars:
    ansible_ssh_pipelining: no

- name: output
  debug:
    msg: "{{ consul_server_cert }}"
  when: enable_debug

- name: Parse output of vault server generate
  set_fact:
    server_cert_parsed: "{{ consul_server_cert.stdout | from_json }}"

- name: Write certificate
  copy:
    content: "{{ server_cert_parsed.data.certificate }}\n"
    dest: "{{ consul_ssl_crt }}"
    group: root
    owner: root
    mode: 0644

- name: Write CA
  copy:
    content: "{{ server_cert_parsed.data.issuing_ca }}\n"
    dest: "{{ consul_ssl_ca }}"
    group: root
    owner: root
    mode: 0644

- name: Write key
  copy:
    content: "{{ server_cert_parsed.data.private_key }}\n"
    dest: "{{ consul_ssl_key }}"
    group: root
    owner: root
    mode: 0644

- name: Write consul env (CONSUL_HTTP_SSL)
  lineinfile:
    path: /root/.bashrc
    regexp: '^export CONSUL_HTTP_SSL='
    line: 'export CONSUL_HTTP_SSL=true'

- name: Write consul env (CONSUL_CACERT)
  lineinfile:
    path: /root/.bashrc
    regexp: '^export CONSUL_CACERT={{ computestacks_consul_ssl_ca }}'
    line: 'export CONSUL_CACERT={{ computestacks_consul_ssl_ca }}'

- name: Write consul env (CONSUL_CLIENT_CERT)
  lineinfile:
    path: /root/.bashrc
    regexp: '^export CONSUL_CLIENT_CERT={{ computestacks_consul_ssl_crt }}'
    line: 'export CONSUL_CLIENT_CERT={{ computestacks_consul_ssl_crt }}'

- name: Write consul env (CONSUL_CLIENT_KEY)
  lineinfile:
    path: /root/.bashrc
    regexp: '^export CONSUL_CLIENT_KEY={{ computestacks_consul_ssl_key }}'
    line: 'export CONSUL_CLIENT_KEY={{ computestacks_consul_ssl_key }}'

- name: Write consul env (CONSUL_HTTP_ADDR)
  lineinfile:
    path: /root/.bashrc
    regexp: '^export CONSUL_HTTP_ADDR='
    line: "export CONSUL_HTTP_ADDR={{ hostvars[inventory_hostname].consul_listen_ip }}:8501"
