---
- name: check if ssl configured
  stat:
    path: "{{ consul_ssl_key }}"
  register: consul_certs_exists

- include_tasks: install_ssl.yml
  when: consul_certs_exists.stat.exists == False

- name: check if exists
  community.general.docker_container_info:
    name: consul
  register: consul_container

- include_tasks: install.yml
  when: not consul_container.exists
