---
- block:
    - name: check if configured
      community.general.docker_container_info:
        name: calico-node
      register: calico_container

    - import_tasks: install.yml
      when: not calico_container.exists
  tags: ['never', 'bootstrap', 'addnode']

- block:
    - name: Write calico network policy
      template:
        src: calico_network.yml.j2
        dest: /root/calico_network.yml
    - name: Apply calico network policy
      shell: "{{ calico_exec }} apply -f /root/calico_network.yml"
      vars:
        ansible_ssh_pipelining: no
    - name: check if network exists
      shell: docker network inspect {{ calico_network_name | lower }} >/dev/null 2>&1
      register: net_exists
      ignore_errors: true
      no_log: True
    - name: Create docker network
      shell: docker network create --driver calico --ipam-driver calico-ipam --subnet={{ calico_network }} {{ calico_network_name | lower }}
      when: net_exists is failed
      vars:
        ansible_ssh_pipelining: no
  delegate_to: "{{ groups['nodes'][0] }}"
  run_once: true
  tags: ['never', 'bootstrap']
