---
- hosts:
    - all
  tags: ['never', 'bootstrap']
  roles:
    - base
    - node_exporter
    - local_dns

- hosts:
    - controller
    - metrics
    - registry
  tags: ['never', 'bootstrap']
  roles:
    - docker
    - cadvisor
    - acme
    - nginx

- hosts:
    - controller
  tags: ['never', 'bootstrap']
  roles:
    - controller_postgres
    - controller_redis
    - vault
    - controller

- hosts: 
    - controller
  tags: ['never', 'vault_unseal']
  roles: 
    - vault_unseal

- hosts:
    - backup_server
  tags: ['never', 'bootstrap']
  roles:
    - backup

- hosts:
    - nodes
  tags: ['never', 'bootstrap']
  roles:
    - node_dnsmasq
    - docker
    - cadvisor
    - haproxy
    - loki_driver
    - andrewrothstein.etcd
    - etcd_config
    - consul
    - node_docker
    - node
    - node_calico
    - cs_agent

- hosts:
    - metrics
  tags: ['never', 'bootstrap']
  roles:
    - loki
    - prometheus
    - alertmanager

- hosts:
    - all
  tags: ['never', 'bootstrap']
  roles:
    - ssh_transfer
    - iptables

- hosts:
    - nodes
  tags: ['never', 'bootstrap']
  roles:
    - node_corosync

- hosts:
    - controller
  tags: ['never', 'bootstrap']
  roles:
    - controller_bootstrap

- hosts: 
    - all
  tags: ['never', 'validate']
  roles: 
    - validate

- hosts:
    - all
  tags: ['never', 'bootstrap']
  tasks:
    - debug:
        msg: "Server is now rebooting. Installation Complete!"
    - name: reboot
      reboot:
        msg: "Ansible rebooting to finalize setup"
        reboot_timeout: 1
      ignore_errors: yes
      no_log: True    
