---
- hosts:
    - all
  tags: ['never', 'bootstrap']
  roles:
    - base
    - docker
    - cadvisor
    - loki_driver
    - node_exporter

- hosts:
    - controller
  tags: ['never', 'bootstrap']
  roles:
    - controller_postgres
    - controller_redis
    - haproxy
    - vault
    - controller

- hosts: 
    - controller
  tags: ['never', 'vault_unseal']
  roles: 
    - vault_unseal

- hosts:
    - backup_server
  tags: ['never', 'bootstrap']
  roles:
    - backup

- hosts:
    - nodes
  tags: ['never', 'bootstrap']
  roles:
    - haproxy
    - andrewrothstein.etcd
    - etcd_config
    - consul
    - node_docker
    - node
    - node_calico
    - node_iptables
    - cs_agent

- hosts:
    - loki_instance
  tags: ['never', 'bootstrap']
  roles:
    - ops_network
    - loki
    - loki_nginx

- hosts:
    - prom_instance
  tags: ['never', 'bootstrap']
  roles:
    - ops_network
    - prometheus_nginx
    - prometheus
    - alertmanager

- hosts:
    - controller
  tags: ['never', 'bootstrap']
  roles:
    - controller_bootstrap

- hosts:
    - nodes
  tags: ['never', 'bootstrap']
  roles:
    - node_corosync

- hosts:
    - all
  roles:
    - ssh_transfer
    - iptables_persist

- hosts:
    - backup_server
    - prom_instance
    - nodes
  tags: ['never', 'bootstrap']
  tasks:
    - name: reboot
      reboot:
        msg: "Ansible rebooting to finalize setup"
        reboot_timeout: 1
      ignore_errors: yes
      no_log: True
