---
##
# Tags
# * bootstrap | Creating a brand new installation from scratch
# * addnode | Adding a new node to an existing Availability Zone

- hosts:
    - all
  tags: ['never', 'bootstrap', 'addnode']
  tasks:
    - name: Load service state
      service_facts:
  roles:
    - base
    - node_exporter
    - local_dns
  any_errors_fatal: true

- hosts:
    - primary_nameserver
    - follower_nameservers
  tags: ['never', 'bootstrap']
  roles:
    - powerdns
  any_errors_fatal: true

- hosts:
    - controller
    - metrics
    - registry
  tags: ['never', 'bootstrap']
  roles:
    - docker
    - cadvisor
    - acme
    - nginx
  any_errors_fatal: true

- hosts:
    - controller
  roles:
    - controller_postgres
    - controller_redis
    - vault
  any_errors_fatal: true

- hosts: 
    - controller
  tags: ['never', 'vault_unseal', 'bootstrap', 'addnode']
  roles: 
    - vault_unseal

- hosts:
    - backup_server
  roles:
    - backup
  any_errors_fatal: true

- hosts:
    - nodes
  serial: 1 # only provision 1 node at a time when adding nodes
  tags: ['never', 'addnode']
  roles:
    - etcd
  any_errors_fatal: true
- hosts:
    - nodes
  tags: ['never', 'bootstrap']
  roles:
    - etcd
  any_errors_fatal: true

- hosts:
    - nodes
  tags: ['never', 'bootstrap', 'addnode']
  roles:
    - node_dnsmasq
    - docker
    - cadvisor
    - haproxy
    - consul
    - node_docker
    - fluentd
    - node
    - cs_agent
    - node_corosync
  any_errors_fatal: true

- hosts:
    - nodes
  roles:
    - node_calico
  any_errors_fatal: true

- hosts:
    - controller
  roles:
    - controller
  any_errors_fatal: true

- hosts:
    - all
  tags: ['never', 'bootstrap', 'addnode']
  roles:
    - iptables
    - ssh_transfer
  any_errors_fatal: true

- hosts:
    - metrics
  roles:
    - loki
    - prometheus
    - alertmanager
  any_errors_fatal: true

- hosts:
    - controller
  tags: ['never', 'bootstrap', 'addnode']
  roles:
    - controller_bootstrap
  any_errors_fatal: true

- hosts: 
    - all
  tags: ['never', 'validate']
  roles: 
    - validate

# Reboot all nodes
- hosts:
    - nodes
  tags: ['never', 'bootstrap']
  tasks:
    - debug:
        msg: "Server is now rebooting. Installation Complete!"
    - name: reboot
      reboot:
        msg: "Ansible rebooting to finalize setup"
        reboot_timeout: 1
      ignore_errors: true
      no_log: True

# Reboot only new nodes
- hosts:
    - nodes
  tags: ['never', 'addnode']
  tasks:
    - block:
        - debug:
            msg: "Installation complete, new nodes are now rebooting."
        - name: reboot
          reboot:
            msg: "Ansible rebooting to finalize setup"
            reboot_timeout: 1
          ignore_errors: true
          no_log: True
      when: etcd_initial_cluster_state == 'existing'
