---
- name: pull latest image
  community.general.docker_image:
    name: "{{ fluentd_image_name }}"
    tag: "{{ fluentd_image_tag }}"
    source: pull

- name: check if fluentd is configured
  stat:
    path: /etc/systemd/system/fluentd.service
  register: fluentd_config_exists

- include_tasks: install.yml
  when: fluentd_config_exists.stat.exists == False

- name: restart
  systemd:
    name: fluentd
    state: restarted
  when: fluentd_config_exists.stat.exists
