---
- name: import elrepo key
  rpm_key:
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    state: present
  when: has_old_kernel

- name: Install Additional Repositories
  yum:
    name:
      - https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: present
  retries: 2
  delay: 2
  when: has_old_kernel

- name: Install newer kernel
  yum:
    name: kernel-lt
    enablerepo: elrepo-kernel
  when: has_old_kernel

- name: Configure grub to select latest kernel
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_DEFAULT"
    line: "GRUB_DEFAULT=0"
    state: present

- name: Update Grub2 Configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
