---
- name: Check if existing resolvconf exists
  stat:
    path: /etc/resolv.conf
  register: resolveconf_exists

- name: copy existing nameservers to dnsmasq
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.dnsmasq
    remote_src: yes
  when: resolveconf_exists.stat.exists == True

- name: install dnsmasq conf
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: install dnsmasq.resolv
  copy:
    src: resolv.dnsmasq
    dest: /etc/resolv.dnsmasq
  when: resolveconf_exists.stat.exists == False

- name: Disable systemd resolve
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  ignore_errors: yes
  no_log: True
