---
- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present  

- name: stop and disable resolvconf
  systemd:
    name: resolvconf
    state: stopped
    enabled: no
  ignore_errors: yes
  no_log: True

- name: Disable systemd resolve
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  ignore_errors: yes
  no_log: True

- name: install dnsmasq conf
  copy:
    src: dnsmasq-debian.conf
    dest: /etc/dnsmasq.conf

- name: install dnsmasq.resolv
  copy:
    src: resolv.dnsmasq
    dest: /etc/resolv.dnsmasq

- name: check if using dhcp conf
  stat:
    path: /etc/dhcp/dhclient.conf
  register: dhcp_conf

- name: modify dhcp conf dns servers
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    regexp: "^prepend domain-name-servers"
    line: "prepend domain-name-servers 127.0.0.1, 8.8.8.8;"
    state: present
  when: dhcp_conf.stat.exists

# For Resolvconf, /etc/resolv.conf may be a symlink, 
# so lets just wipe that out before we install our version
- name: clean resolvconf
  file:
    path: /etc/resolv.conf
    state: absent

- name: install new resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: initialize dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: ensure dnsmasq is running
  shell: "systemctl status dnsmasq >/dev/null 2>&1"
  register: dnsmasq_is_active
  ignore_errors: yes
  no_log: True
  vars:
    ansible_ssh_pipelining: no
    
- fail:
    msg: "dnsmasq is not running"
  when: dnsmasq_is_active is failed

