---
- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present  


- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: install new resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: initialize dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: ensure dnsmasq is running
  shell: "systemctl status dnsmasq >/dev/null 2>&1"
  register: dnsmasq_is_active
  ignore_errors: yes
  no_log: True
  vars:
    ansible_ssh_pipelining: no
    
- fail:
    msg: "dnsmasq is not running"
  when: dnsmasq_is_active is failed

