---
- name: install redis
  package:
    name:
      - redis
    state: present
    update_cache: yes

- name: disable redis snapshots
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^save ""'
    line: 'save ""'

- name: start
  service:
    name: redis-server
    enabled: yes
    state: restarted
