---
- name: install
  package:
    name: redis-server
    state: present

- name: install config
  copy:
    src: redis-debian.conf
    dest: /etc/redis/redis.conf

- name: start
  service:
    name: redis-server
    enabled: yes
    state: restarted
