---
- name: Install redis apt key
  shell: "curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg"

- name: Add apt repo
  shell: echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb bullseye main" | tee /etc/apt/sources.list.d/redis.list

- name: install redis
  package:
    name:
      - redis
      - redis-server
    state: present
    update_cache: yes

- name: disable redis snapshots
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^save ""'
    line: 'save ""'

- name: start
  service:
    name: redis-server
    enabled: yes
    state: restarted
