---
- name: check if existing iptables file exists
  stat:
    path: /usr/local/bin/cs-recover_iptables
  register: existing_iptables

- include_tasks: update.yml
  when: existing_iptables.stat.exists

- name: install config script
  template:
    src: iptables.sh.j2
    dest: /usr/local/bin/cs-recover_iptables
    owner: root
    group: root
    mode: '0655'
  notify: activate rules
  when: existing_iptables.stat.exists == False

- name: install systemd
  copy:
    src: iptables.service
    dest: /etc/systemd/system/cs-iptables.service
  notify: reload iptables systemd
