---
- name: install config script
  template:
    src: iptables.sh.j2
    dest: /usr/local/bin/cs-recover_iptables
    owner: root
    group: root
    mode: '0655'

- name: install systemd
  copy:
    src: iptables.service
    dest: /etc/systemd/system/cs-iptables.service

- name: reload systemd
  systemd:
    name: "cs-iptables.service"
    enabled: yes
    daemon_reload: yes

- name: activate rules
  command: /usr/local/bin/cs-recover_iptables
