---
- name: pull image
  community.general.docker_image:
    name: "{{ cadvisor_image }}"
    tag: "{{ cadvisor_image_tag }}"
    source: pull

- name: install systemd
  template:
    src: cadvisor.service.j2
    dest: /etc/systemd/system/cadvisor.service

- name: start prometheus
  systemd:
    name: cadvisor
    state: started
    enabled: yes
    daemon_reload: yes
