---
- name: cadvisor | pull latest image
  community.general.docker_image:
    name: "{{ cadvisor_image }}"
    tag: "{{ cadvisor_image_tag }}"
    source: pull

- name: cadvisor | configure systemd
  template:
    src: cadvisor.service.j2
    dest: /etc/systemd/system/cadvisor.service

- name: cadvisor | reload and start
  systemd:
    name: cadvisor
    state: restarted
    enabled: yes
    daemon_reload: yes
