---
config_directory: "/etc/computestacks"

region_name: "dev"
availability_zone_name: "{{ region_name }}-a"

motd_info:
  - "    HOST:    ": "{{ hostvars[inventory_hostname].ansible_hostname }}"
  - "      IP:    ": "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
  - "  REGION:    ": "{{ region_name }}"
  - "      AZ:    ": "{{ availability_zone_name }}"

motd_info_controller:
  - "    HOST:    ": "{{ hostvars[inventory_hostname].ansible_hostname }}"
  - "      IP:    ": "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"

tmux_url: "https://gist.githubusercontent.com/kwatson/45a298891981e2323eed3e118a3d5da7/raw/ff7eb5ba7afbccb11df6470290ab6f520c2a128d/.tmux.conf"

##
# Cloud Platform Specifics
cloud_platform: "generic"
platform_do_token: "" # DigitalOcean Personal Access token

##
# CloudFlare DNS Challenge
cloudflare_base_api: "https://api.cloudflare.com/client/v4"
acme_challenge_method: "http" # or cloudflare
acme_cf_token: "" # API Token
acme_cf_account: "" # Account ID
acme_cf_zone: "" # Zone ID (Optional)

##
# CS Settings
# Default User
cs_admin_email: root@localhost
cs_admin_password: changeme

##
# CS DNS

# AutoDNS
dns_autodns_json_endpoint: "api.autodns.com"
dns_autodns_endpoint: "{{ hostvars[groups['controller'][0]].autodns_endpoint | default('gateway.autodns.com') }}"
dns_autodns_primaryns: "{{ hostvars[groups['controller'][0]].autodns_master_ns | default('a.ns14.net') }}"
dns_autodns_context: "{{ hostvars[groups['controller'][0]].autodns_context | default('4') }}"
dns_autodns_username: "{{ hostvars[groups['controller'][0]].autodns_username | default('') }}"
dns_autodns_password: "{{ hostvars[groups['controller'][0]].autodns_password | default('') }}"

dns_allowed_drivers:
  - autodns
  - powerdns

dns_driver: "{{ (hostvars[groups['controller'][0]].dns_driver | default('powerdns')) }}"

dns_valid_driver: "{{ dns_driver in dns_allowed_drivers }}"


# Node:
etcd_listen_ip: ""
node_resolvers: []
