---
overwrite_resolvconf: true
config_directory: "/etc/computestacks"

cs_diag_url: "https://gist.githubusercontent.com/kwatson/1022d337d2a775264586056819366d2d/raw/7361d2e58a0b1c6a3babc66afdbfdad0729775c0/cs-diag-without-google.sh"
cs_diag_file: /usr/local/bin/cs-diagnostic

region_name: "dev"
availability_zone_name: "{{ region_name }}-a"

motd_info:
  - "    HOST:    ": "{{ hostvars[inventory_hostname].ansible_hostname }}"
  - "      IP:    ": "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
  - "  REGION:    ": "{{ region_name }}"
  - "      AZ:    ": "{{ availability_zone_name }}"

tmux_url: "https://gist.githubusercontent.com/kwatson/45a298891981e2323eed3e118a3d5da7/raw/ff7eb5ba7afbccb11df6470290ab6f520c2a128d/.tmux.conf"

is_centos_7: "{{ (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7') or (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7') }}"
has_old_kernel: "{{ ansible_kernel is version('5', '<') }}"

##
# Cloud Platform Specifics
cloud_platform: "generic"
platform_do_token: "" # DigitalOcean Personal Access token

##
# CloudFlare DNS Challenge
cloudflare_base_api: "https://api.cloudflare.com/client/v4"
acme_challenge_method: "http" # or cloudflare
acme_cf_token: "" # API Token
acme_cf_account: "" # Account ID
acme_cf_zone: "" # Zone ID (Optional)

##
# CS Settings
# Default User
cs_admin_create: false # CS Support user is already created by default
cs_admin_email: root@localhost
cs_admin_password: changeme

etcd_initial_cluster_state: ""
