---
overwrite_resolvconf: true
config_directory: "/etc/computestacks"

cs_diag_url: "https://gist.githubusercontent.com/kwatson/1022d337d2a775264586056819366d2d/raw/7361d2e58a0b1c6a3babc66afdbfdad0729775c0/cs-diag-without-google.sh"
cs_diag_file: /usr/local/bin/cs-diagnostic

motd_info:
  - "    HOST:    ": "{{ hostvars[inventory_hostname].ansible_hostname }}"
  - "      IP:    ": "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
  - "  REGION:    ": "{{ global_region_name }}"

global_region_name: ""

tmux_url: "https://gist.githubusercontent.com/kwatson/45a298891981e2323eed3e118a3d5da7/raw/ff7eb5ba7afbccb11df6470290ab6f520c2a128d/.tmux.conf"

is_centos_7: "{{ (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7') or (ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7') }}"
has_old_kernel: "{{ ansible_kernel is version('5', '<') }}"

##
# Cloud Platform Specifics
cloud_platform: "generic"
platform_do_token: "" # DigitalOcean Personal Access token

##
# CloudFlare DNS Challenge
cloudflare_base_api: "https://api.cloudflare.com/client/v4"
acme_challenge_method: "http" # or cloudflare
acme_cf_token: "" # API Token
acme_cf_account: "" # Account ID
acme_cf_zone: "" # Zone ID (Optional)
