---
- name: fetch controller ssh keys
  slurp:
    src: "{{ item }}"
  register: ssh_certs
  run_once: true
  delegate_to: "{{ groups['controller'][0] }}"
  with_items:
    - "{{ ssh_keys_directory }}/id_ed25519.pub"
    - /root/.ssh/id_ed25519.pub

- name: register controller ssh keys
  set_fact:
    ssh_app: "{{ ssh_certs.results[0].content|b64decode }}"
    ssh_admin: "{{ ssh_certs.results[1].content|b64decode }}"
  
- name: write ssh keys
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ ssh_app }}"
    - "{{ ssh_admin }}"

- name: verify controller can connect
  shell: "ssh -o 'StrictHostKeyChecking no' {{ inventory_hostname }} -C date"
  delegate_to: "{{ groups['controller'][0] }}"
  vars:
    ansible_ssh_pipelining: no
