---
calico_node_image: "quay.io/calico/node:release-v2.6"

# calico_src: https://github.com/projectcalico/calicoctl/releases/download/v1.6.5/calicoctl
calico_src: https://cdn.computestacks.net/packages/calico/calicoctl-v1.6.5

# calico_ipam_src: https://github.com/projectcalico/libnetwork-plugin/releases/download/v1.1.3/libnetwork-plugin
calico_ipam_src: https://cdn.computestacks.net/packages/calico/libnetwork-plugin-v1.1.3

calico_network: ""
calico_network_name: ""
calico_network_ipip: false

container_network_mtu: 1500

calico_conf_dir: /etc/calico
calico_exec: "/usr/local/bin/calicoctl"
calico_ipam_exec: "/usr/local/bin/calico-libnetwork"
calico_ipam_conf: "{{ calico_conf_dir }}/calico-ipam.env"
calico_cli_conf: "{{ calico_conf_dir }}/calicoctl.cfg"

network_manager_dir: "/etc/NetworkManager/conf.d"
network_manager_conf: "{{ network_manager_dir }}/calico.conf"

etcd_listen_ip: 127.0.0.1

##
# etcd certificates
etcd_data_dir: /var/lib/etcd
etcd_certs_dir: "{{ etcd_data_dir }}/certs"
etcd_ca_file: "{{ etcd_certs_dir }}/ca.crt"
etcd_client_cert_file: "{{ etcd_certs_dir }}/client/client.crt"
etcd_client_key_file: "{{ etcd_certs_dir }}/client/client.key"