---
- name: loki_nginx | install required pip packages
  pip:
    name: passlib

- name: loki_nginx | check nginx directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/nginx
    - /etc/nginx/loki
    - /etc/nginx/loki/conf.d
    - /etc/nginx/loki/passwords

- name: loki_nginx | nginx install image
  community.general.docker_image:
    name: "{{ nginx_image }}"
    tag: "{{ nginx_image_tag }}"
    source: pull

- name: loki_nginx | nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/loki/nginx.conf

- name: loki_nginx | loki vhost conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/loki/conf.d/default.conf

- name: loki_nginx | nginx password
  community.general.htpasswd:
    path: /etc/nginx/loki/passwords/loki.htpasswd
    name: "{{ loki_nginx_username }}"
    password: "{{ loki_nginx_password }}"

# - debug:
#     msg: "{{ hostvars[groups['loki_instance'][0]]['loki_container_name'] }}"

- name: loki_nginx | run container
  community.general.docker_container:
    name: loki-nginx
    detach: yes
    network_mode: "container:loki-logs"
    image: "{{ nginx_full_image }}"
    state: started
    container_default_behavior: compatibility
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: "2"
    restart_policy: "unless-stopped"
    volumes:
      - "/etc/nginx/loki/nginx.conf:/etc/nginx/nginx.conf:Z"
      - "/etc/nginx/loki/conf.d:/etc/nginx/conf.d:Z"
      - "/etc/nginx/loki/passwords:/etc/nginx/passwords:Z"
