---
postgres_user: computestacks
postgres_cs_password: "ch4ng3m3"

yum_repo_url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"

psql_version: "13"
psql_base_path: "/usr/pgsql-{{ psql_version }}"
psql_data_path: "/var/lib/pgsql/{{ psql_version }}"