---
postgres_user: computestacks
postgres_cs_password: "ch4ng3m3" # pwgen -s 32 1

psql_version: 17

psql_initdb_cmd: "/usr/lib/postgresql/{{ psql_version }}/bin/initdb"
psql_data_path: "/etc/postgresql/{{ psql_version }}/main"

psql_service_name: "postgresql"
