---
- name: write pdns conf
  template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf

- name: ensure postgresql is running
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: check if db configured
  postgresql_ping:
    db: pdns
    login_host: localhost
    login_user: pdns
    login_password: "{{ pdns_db_pass }}"
  register: pdns_psql_db_up

- block:
    - name: create psql pdns db
      postgresql_db:
        name: pdns
        encoding: UTF-8
        template: template0
        state: present
      become_user: postgres
      become: true
      become_method: su

    - name: create psql pdns role
      postgresql_user:
        name: pdns
        db: pdns
        role_attr_flags: "superuser,login"
        password: "{{ pdns_db_pass }}"
        state: present
      become: true
      become_user: postgres
      become_method: su

    - name: create psql replication user
      postgresql_user:
        name: repuser
        role_attr_flags: "replication"
        state: present
      become: true
      become_user: postgres
      become_method: su

    - name: psql import base schema
      postgresql_db:
        name: pdns
        state: restore
        target: /usr/share/doc/pdns-backend-pgsql/schema.pgsql.sql
      become: true
      become_user: postgres
      become_method: su
  when: not pdns_psql_db_up.is_available
