---
- name: Adjust postgres listen ip
  lineinfile:
    path: "{{ pdns_postgresql_conf }}"
    regexp: "listen_address"
    line: "listen_addresses = 'localhost,{{ postgres_ip }}'"
  notify: Restart Postgres

- name: Add followers to leader pg
  postgresql_pg_hba:
    dest: "{{ pdns_postgresql_hba_conf }}"
    contype: host
    users: "{{ pdns_replication_user }}"
    databases: replication
    method: trust
    source: "{{ hostvars[groups['follower_nameservers'][0]].postgres_ip }}"
  notify: Restart Postgres

- meta: flush_handlers
