---
- include_tasks: install_postgres.yml
  when: ansible_facts.services['postgresql.service'] is not defined

- include_tasks: install.yml
  when: ansible_facts.services['pdns.service'] is not defined

- name: upgrade pdns packages
  apt:
    name:
      - "pdns-server"
      - "pdns-backend-pgsql"
    state: latest
  when: ansible_facts.services['pdns.service'] is defined
