---
- include_tasks: install_postgres.yml
  when: (ansible_facts.services['postgresql.service'] is not defined) or
        (ansible_facts.services['postgresql.service']['status'] != "running")

- include_tasks: install_pg_leader.yml
  when: "'primary_nameserver' in group_names"

- include_tasks: install.yml
  when: (ansible_facts.services['pdns.service'] is not defined) or
        (ansible_facts.services['pdns.service']['state'] != "running")

- name: upgrade pdns packages
  apt:
    name:
      - "pdns-server"
      - "pdns-backend-pgsql"
    state: latest
  when:
    - ansible_facts.services['postgresql.service'] is defined
    - ansible_facts.services['postgresql.service']['status'] == "enabled"
