---
- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
      - python3-psycopg2
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure PostgreSQL is enabled and running
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
    enabled: true
