---
- name: Ensure SELinux is enabled
  fail:
    msg: SELinux is disabled
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_selinux == False or ansible_selinux.status == 'disabled'

- name: Ensure portal domain exists
  fail:
    msg: "'cs_portal_domain' is not defined"
  when: cs_portal_domain == ""

- name: Ensure registry domain exists
  fail:
    msg: "'cs_registry_domain' is not defined"
  when: cs_registry_domain == ""

- name: Ensure Floating IP exists
  fail:
    msg: "'floating_ip' is not defined"
  when: floating_ip == ""

- name: Ensure region name defined
  fail:
    msg: "'region_name' is not defined"
  when: region_name == ""

- name: Ensure AZ name defined
  fail:
    msg: "'availability_zone_name' is not defined"
  when: availability_zone_name == ""

- name: Ensure default app url is defined
  fail:
    msg: "'cs_app_url' is not defined"
  when: cs_app_url == ""

- name: Ensure correct linux variant
  fail:
    msg: "Invalid OS distribution. Only CentOS 7 and Debian 10 are supported."
  when:
    - ansible_distribution != "CentOS"
    - ansible_distribution != 'Debian'

- name: Ensure supported linux version (CentOS)
  fail:
    msg: "Invalid CentOS version. Only version 7 is supported"
  when: 
    - ansible_facts['distribution_major_version']|int < 7 or ansible_facts['distribution_major_version']|int > 7
    - ansible_distribution == 'CentOS'

- name: Ensure supported linux version (Debian)
  fail:
    msg: "Invalid Debian version. Only version 10 is supported"
  when: 
    - ansible_facts['distribution_major_version']|int == "10"
    - ansible_distribution == 'Debian'

- name: Ensure DigitalOcean token exists
  fail:
    msg: "DigitalOcean is selected, but missing platform_do_token"
  when:
    - "cloud_platform == 'digitalocean'"
    - "platform_do_token == ''"

- name: Ensure CloudFlare Token is present
  fail:
    msg: Missing CloudFlare API Token
  when:
    - "acme_challenge_method == 'cloudflare'"
    - "acme_cf_token == ''"

- name: Ensure CloudFlare Account ID is present
  fail:
    msg: Missing CloudFlare API Token
  when:
    - "acme_challenge_method == 'cloudflare'"
    - "acme_cf_token == ''"

- name: Ensure default admin credentials are not present
  block:
    - name: ensure admin email present
      fail:
        msg: Missing cs_admin_email
      when: "cs_admin_email == '' or cs_admin_email == 'root@localhost'"
    - name: ensure admin password present
      fail:
        msg: Missing cs_admin_password
      when: "cs_admin_password == '' or cs_admin_password == 'changeme'"
  when: cs_admin_create

- name: Validate etcd_initial_cluster_state
  fail:
    msg: "etcd_initial_cluster_state must be either new or existing"
  when:
    - "'nodes' in group_names"
    - "etcd_initial_cluster_state != 'new'"
    - "etcd_initial_cluster_state != 'existing'"

- name: Validate etcd master
  fail:
    msg: "First node must have etcd_initial_cluster_state set to new"
  when:
    - "inventory_hostname == groups['nodes'][0]"
    - "etcd_initial_cluster_state != 'new'"
