---
- name: Generate Secret Key
  block:
    - command: openssl rand -hex 64
      register: secret_key_raw
    - set_fact:
        secret_key: "{{ secret_key_raw.stdout }}"
  when: secret_key == ""

- name: Generate Auth Key
  block:  
    - command: openssl rand -hex 64
      register: secret_auth_key_raw
    - set_fact:
        secret_auth_key: "{{ secret_auth_key_raw.stdout }}"
  when: secret_auth_key == ""

- name: Write cstacks settings
  template:
    src: default-computestacks.j2
    dest: "{{ cs_environmental_file }}"
    mode: 0640

- name: branding css
  get_url:
    url: "{{ branding_css_url }}"
    dest: "{{ branding_directory }}/application.css"

- name: branding css map
  get_url:
    url: "{{ branding_css_map_url }}"
    dest: "{{ branding_directory }}/application.css.map"

- name: branding login image
  get_url:
    url: "{{ branding_login_img_url }}"
    dest: "{{ branding_directory }}/logo-login.png"

- name: branding favicon
  file:
    path: "{{ branding_directory }}/favicon.ico"
    state: touch

##
# Controller Docker Image
- name: pull container image
  docker_image:
    name: "{{ controller_image_path }}"
    source: pull
