---
- import_tasks: install.yml
  tags: ['never', 'bootstrap']

# ##
# # Generate Bootstrap
- block:
    - name: Slurp and store wildcared cert
      slurp:
        src: "{{ data_directory }}/.ssl_wildcard/sharedcert.pem"
      register: lb_shared_cert_raw

    - name: Decode certificate for assignment
      set_fact:
        lb_shared_cert: "{{ lb_shared_cert_raw.content | b64decode }}"
    - name: Create bootstrap file
      template:
        src: bootstrap.rake
        dest: "{{ rake_tasks_directory }}/bootstrap.rake"
  tags: ['never', 'bootstrap', 'addnode']
