---
- import_tasks: install.yml
  tags: ['never', 'bootstrap']

# Ensure we always have an updated cstacks script
- block:
    - name: controller | cstacks script
      copy:
        src: cstacks.sh
        dest: /usr/local/bin/cstacks
        mode: 0740
    - name: controller | cstacks bash completion
      copy:
        src: cstacks_completion.sh
        dest: /etc/bash_completion.d/cstacks.sh
        mode: 0740
  tags: ['never', 'bootstrap', 'addnode']

- import_tasks: generate_bootstrap.yml
  tags: ['never', 'bootstrap', 'addnode']
