---
- name: Generate ComputeStacks SSH Key
  openssh_keypair:
    path: "{{ ssh_keys_directory }}/id_ed25519"
    comment: ComputeStacks Portal
    type: ed25519
    owner: root
    group: root
    state: present
    regenerate: never
