---
- name: check if ssh key exists
  stat:
    path: "{{ ssh_keys_directory }}/id_ed25519"
  register: ssh_key_exists
  
- name: Generate ComputeStacks SSH Key
  openssh_keypair:
    path: "{{ ssh_keys_directory }}/id_ed25519"
    comment: ComputeStacks Portal
    type: ed25519
    owner: root
    group: root
  when: ssh_key_exists.stat.exists == False
