---
- name: Ensure haproxy certs directory exists
  file:
    path: "/etc/haproxy/certs"
    state: directory

- name: Generate a Self Signed OpenSSL certificate
  openssl_privatekey:
    path: "/etc/haproxy/certs/self.key"
- openssl_csr:
    path: "/etc/haproxy/certs/self.csr"
    privatekey_path: "/etc/haproxy/certs/self.key"
    common_name: "{{ ansible_hostname }}"
- openssl_certificate:
    path: "/etc/haproxy/certs/self.crt"
    privatekey_path: "/etc/haproxy/certs/self.key"
    csr_path: "/etc/haproxy/certs/self.csr"
    provider: selfsigned

- name: Remove OpenSSL CSR
  file:
    path: "/etc/haproxy/certs/self.csr"
    state: absent

- name: Combine self signed for HAProxy
  assemble:
    src: '/etc/haproxy/certs'
    dest: '/etc/haproxy/certs/selfsigned.pem'

- name: Remove self signed parts
  file:
    path: "/etc/haproxy/certs/self.crt"
    state: absent
- file:
    path: "/etc/haproxy/certs/self.key"
    state: absent

- name: Setup Container Registry Certificates
  file:
    path: '{{ registry_ssl_directory }}'
    state: directory
- openssl_privatekey:
    path: "{{ registry_ssl_directory }}/key.pem"
- openssl_csr:
    path: "{{ registry_ssl_directory }}/reg.csr"
    privatekey_path: "{{ registry_ssl_directory }}/key.pem"
    common_name: "{{ ansible_hostname }}"
- openssl_certificate:
    path: "{{ registry_ssl_directory }}/cert.cer"
    privatekey_path: "{{ registry_ssl_directory }}/key.pem"
    csr_path: "{{ registry_ssl_directory }}/reg.csr"
    provider: selfsigned
- file:
    path: "{{ registry_ssl_directory }}/reg.csr"
    state: absent
