---
- name: pull image
  community.general.docker_image:
    name: "{{ alertmanager_image }}"
    tag: "{{ alertmanager_image_tag }}"
    source: pull

- name: create alertmanager volume
  community.general.docker_volume:
    name: alertmanager-data
    state: present

- name: create directories
  file:
    path: "/etc/prometheus"
    state: directory

- name: install alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml

- name: install systemd
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service

- name: start alertmanager
  systemd:
    name: alertmanager
    state: started
    enabled: yes
    daemon_reload: yes
