---
- name: ensure etcd_listen_ip is set
  fail:
    msg: Missing etcd_listen_ip
  when: "etcd_listen_ip == ''"
  
- name: Install etcd package
  apt:
    name: 
      - etcd-server
      - etcd-client
    state: latest

- block:
    - name: Check if etcd is provisioned
      shell: "ETCDCTL_ENDPOINT=\"https://{{ etcd_listen_ip }}:2379\" {{ etcd_check_alive_cmd }}"
      register: etcd_provisioned      
      ignore_errors: true
      no_log: True
    - include_tasks: provision.yml
      when: etcd_provisioned.rc > 0
  vars:
    ansible_ssh_pipelining: no
