---
- name: ensure etcd_listen_ip is set
  fail:
    msg: Missing etcd_listen_ip
  when: "etcd_listen_ip == ''"
  
- name: Install etcd package
  apt:
    name: 
      - etcd-server
      - etcd-client
    state: latest

- name: stop etcd
  systemd:
    name: etcd
    state: stopped
    
- name: wipe out existing etcd db
  file:
    path: "{{ etcd_member_dir }}"
    state: absent

- name: Write etcd config file (new)
  template:
    src: etcd.conf.j2
    dest: "{{ etcd_conf }}"
  when: "etcd_initial_cluster_state == 'new'"

- name: Write etcd config file (existing)
  template:
    src: etcd-existing.conf.j2
    dest: "{{ etcd_conf }}"
  when: "etcd_initial_cluster_state == 'existing'"

- name: Check if certs exist
  stat:
    path: "{{ etcd_cert_file }}"
  register: cert_configured

- include_tasks: vault-certs.yml  
  when: cert_configured.stat.exists == False

- name: start & enable etcd
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes

##
# Joining
- block:
    - name: determine if node already exists
      shell: "ETCDCTL_ENDPOINT=\"https://{{ hostvars[groups['nodes'][0]].etcd_listen_ip }}:2379\" {{ etcd_command_base }} member list | grep {{ etcd_listen_ip }} | wc -l"
      register: existing_member
      vars:
        ansible_ssh_pipelining: no
      delegate_to: "{{ groups['nodes'][0] }}"
    - debug:
        var: existing_member.stdout
    - include_tasks: join_existing.yml  
      when: "existing_member.stdout == '0'" 
  when: "etcd_initial_cluster_state == 'existing'"

