---
- name: ensure calico exists
  community.general.docker_container_info:
    name: calico-node
  register: calico_container

- name: attempt calico recovery
  shell: run_calico >/dev/null 2>&1
  ignore_errors: yes
  no_log: True
  vars:
    ansible_ssh_pipelining: no
  when: not calico_container.exists

- name: attempt alternate calico recovery
  block:
    - name: remove existing calico node
      community.general.docker_container:
        name: portal
        state: absent
    - name: attempt calico recovery
      shell: run_calico >/dev/null 2>&1
      ignore_errors: yes
      no_log: True
      vars:
        ansible_ssh_pipelining: no
    - name: check calico once again
      community.general.docker_container_info:
        name: calico-node
      register: final_calico_container
    - name: calico offline
      fail:
        msg: Calico is offline
      when:
        - final_calico_container.exists
        - "final_calico_container.container['State']['Status'] != 'running'"
    - name: calico does not exist
      fail:
        msg: Calico does not exist
      when: not final_calico_container.exists
  when:
    - calico_container.exists
    - "calico_container.container['State']['Status'] != 'running'"
