---
- name: create ops network
  community.general.docker_network:
    name: ops
    state: present

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/loki
    - /var/lib/loki

- name: install config
  copy:
    src: loki-config.yml
    dest: /etc/loki/loki-config.yml

- name: pull image
  community.general.docker_image:
    name: "{{ loki_image }}"
    tag: "{{ loki_image_tag }}"
    source: pull

- name: create loki volume
  community.general.docker_volume:
    name: loki-data
    state: present

- name: install loki systemd
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service

- name: start loki
  systemd:
    name: loki
    state: started
    enabled: yes
    daemon_reload: yes
