---
- name: create ops network
  community.general.docker_network:
    name: ops
    state: present

- name: create loki volume
  community.general.docker_volume:
    name: loki-data
    state: present

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/loki
    - /var/lib/loki

- name: install config
  copy:
    src: loki-config.yml
    dest: /etc/loki/loki-config.yml
