---
- name: loki | check if plugin exists
  shell: docker plugin inspect loki >/dev/null 2>&1
  register: loki_plugin_exists
  ignore_errors: yes
  no_log: True

# https://grafana.com/docs/loki/latest/clients/docker-driver/
- name: loki | install docker driver
  shell: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions >/dev/null 2>&1
  when: loki_plugin_exists is failed

- name: loki | create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/loki
    - /var/lib/loki

- name: loki | install config
  copy:
    src: loki-config.yml
    dest: /etc/loki/loki-config.yml

- name: loki | pull image
  community.general.docker_image:
    name: "{{ loki_image }}"
    tag: "{{ loki_image_tag }}"
    source: pull

- name: loki | local hosts entry
  lineinfile:
    dest: /etc/hosts
    regexp: "127.0.0.1 loki.local"
    line: "127.0.0.1 loki.local"
    state: present

- name: loki | run container
  community.general.docker_container:
    name: "loki-logs"
    detach: yes
    image: "{{ loki_full_image }}"
    state: started
    container_default_behavior: compatibility
    network_mode: ops
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: "2"
    restart_policy: "unless-stopped"
    published_ports:
      - "{{ loki_nginx_listen }}:{{ loki_nginx_listen }}"
    volumes:
      - "/etc/loki/loki-config.yml:/etc/loki/local-config.yaml:Z"
      - "/var/lib/loki:/loki:Z"
