---
- name: loki | check if exists
  shell: "docker inspect loki-logs >/dev/null 2>&1"
  register: loki_exists
  ignore_errors: yes
  no_log: True

- include_tasks: install.yml
  when: loki_exists is failed
