---
- import_tasks: install.yml
  when: ansible_facts.services['loki.service'] is not defined
  tags: ['never', 'bootstrap']

- name: loki | pull image
  community.general.docker_image:
    name: "{{ loki_image }}"
    tag: "{{ loki_image_tag }}"
    source: pull

- name: loki | configure systemd
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service

- name: loki | restart
  systemd:
    name: loki
    state: restarted
    enabled: yes
    daemon_reload: yes
