---
enable_debug: false

##
# vars from inventory
cs_portal_domain: ""
consul_listen_ip: "127.0.0.1"
consul_listen_port: 8501
consul_token: "" # placeholder

##
# Agent Configuration
docker_api_version: "1.41"
agent_image: "ghcr.io/computestacks/cs-docker-borg:latest"
agent_download_url: "https://f.cscdn.cc/file/cstackscdn/packages/cs-agent/cs-agent-amd64.tar.gz"

# Paths
agent_config_path: /etc/computestacks
agent_certs_dir: "{{ agent_config_path }}/certs"
agent_docker_certs_dir: "{{ agent_certs_dir }}/docker"
agent_consul_certs_dir: "{{ agent_certs_dir }}/consul"

# Backup Configuration
backups_enabled: true
backups_check_freq: "*/2 * * * *"
backups_prune_freq: "15 1 * * *"
backups_key: "changme!"

# Backup NFS
backup_uses_nfs: "{{ groups['backup_server'] is defined and (groups['backup_server']|length>0) | lower }}"
backup_nfs_host: "{% if backup_uses_nfs == 'true' %}{{ hostvars[groups['backup_server'][0]].node_ip }}{% else %}127.0.0.1{% endif %}"
nfs_host_path: "/var/nfsshare/volume_backups"

# Backup NFS SSH Settings
backup_nfs_ssh_user: "root"
backup_nfs_ssh_port: "{% if backup_uses_nfs == 'true' %}{{ hostvars[groups['backup_server'][0]].ssh_port }}{% else %}22{% endif %}"
backup_nfs_ssh_keyfile: "/root/.ssh/id_ed25519" # path to private key on the node
backup_nfs_opts: ",async,noatime,rsize=32768,wsize=32768"
backup_nfs_create_path: true