---
- name: Ensure vault is running
  community.docker.docker_container:
    name: vault-bootstrap
    state: started

- name: check if vault is sealed
  shell: vault operator key-status >/dev/null 2>&1
  register: vault_sealed
  ignore_errors: yes
  no_log: True
  vars:
    ansible_ssh_pipelining: no

- include_tasks: unseal.yml
  when: vault_sealed is failed