---
- name: node_exporter | exists?
  shell: systemctl status node_exporter >/dev/null 2>&1
  register: node_exporter_exists
  ignore_errors: yes
  no_log: True

- include_tasks: install.yml
  when: node_exporter_exists is failed
