---
- name: install node exporter
  apt:
    name: prometheus-node-exporter
    state: latest

- name: activate and run
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes