---
- include_tasks: install_centos.yml
  when:
    - ansible_distribution == 'CentOS' 
    - ansible_facts.services['node_exporter.service'] is not defined

- include_tasks: install_debian.yml
  when:
    - ansible_distribution == 'Debian' 
    - ansible_facts.services['prometheus-node-exporter.service'] is not defined
