---
- name: read key file
  command: cat {{ item }}
  register: unseal_keys
  with_items:
    - "{{ vault_storage_path }}/keys/unseal_key_0"
    - "{{ vault_storage_path }}/keys/unseal_key_1"
    - "{{ vault_storage_path }}/keys/unseal_key_2"
  delegate_to: "{{ groups['controller'][0] }}"

- name: unseal with keys
  command: |
    {{ vault_command }} operator unseal {{ item.stdout }}
  with_items: "{{unseal_keys.results}}"
  register: vault_unseal_results  
  retries: 3
  delay: 5
  until: vault_unseal_results.rc == 0
