---
- name: create user for borg
  user:
    name: "{{ agent_ssh_user }}"

- name: ensure borg remote path exists
  file:
    path: "{{ ssh_agent_host_path }}"
    state: directory
    mode: '0770'
    owner: "{{ agent_ssh_user }}"
    group: "{{ agent_ssh_group }}"
