---
- name: Set vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes

- name: Set nf_conntrack
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: "1000000"
    state: present
    reload: yes

- name: "Set net.core.netdev_max_backlog"
  sysctl:
    name: net.core.netdev_max_backlog
    value: "30000"
    state: present
    reload: yes

- name: "Set net.core.rmem_max"
  sysctl:
    name: net.core.rmem_max
    value: "134217728"
    state: present
    reload: yes

- name: "Set net.core.wmem_max"
  sysctl:
    name: net.core.wmem_max
    value: "134217728"
    state: present
    reload: yes

- name: "Set net.ipv4.tcp_max_syn_backlog"
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: "3240000"
    state: present
    reload: yes

- name: "Set net.ipv4.tcp_rmem"
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "4096 87380 67108864"
    state: present
    reload: yes

- name: "Set net.ipv4.tcp_wmem"
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "4096 87380 67108864"
    state: present
    reload: yes

- name: "Set net.core.somaxconn"
  sysctl:
    name: net.core.somaxconn
    value: "500"
    state: present
    reload: yes

- name: "Set fs.file-max"
  sysctl:
    name: fs.file-max
    value: "1000000"
    state: present
    reload: yes

- name: "Set net.ipv4.tcp_mem"
  sysctl:
    name: net.ipv4.tcp_mem
    value: "765828 1021104 3063312"
    state: present
    reload: yes

# This was found on an ubuntu 16.04 container node -- not sure if it's useful.
# - name: "Set nfs.aio-max-nr"
#   sysctl:
#     name: fs.aio-max-nr
#     value: "2097152"
#     state: present
#     reload: yes
