---
- name: setup directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/prometheus/cadvisor
    - /etc/prometheus/node_exporter
    - /etc/prometheus/haproxy

- name: install prom config
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: install cadvisor config
  template:
    src: cadvisor.yml
    dest: "/etc/prometheus/cadvisor/{{ availability_zone_name }}.yml"

- name: install node_exporter config
  template:
    src: node_exporter.yml
    dest: "/etc/prometheus/node_exporter/{{ availability_zone_name }}.yml"

- name: install haproxy config
  template:
    src: haproxy.yml
    dest: "/etc/prometheus/haproxy/{{ availability_zone_name }}.yml"

- name: install alerts_containers
  template:
    src: alerts_containers.yml.j2
    dest: /etc/prometheus/alerts_containers.yml
