---
- name: create directories
  file:
    path: "/etc/prometheus"
    state: directory

- name: install files
  copy:
    src: "{{ item }}"
    dest: /etc/prometheus/
  loop:
    - alerts_node.yml
    - alerts_prometheus.yml

- name: check if volume exists
  shell: docker volume inspect prometheus-data >/dev/null 2>&1
  register: prometheus_vol_exists
  ignore_errors: true
  no_log: True
  vars:
    ansible_ssh_pipelining: no

- name: create prometheus volume
  community.general.docker_volume:
    name: prometheus-data
  when: prometheus_vol_exists is failed

- name: install systemd
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
