---
- import_tasks: install.yml
  when: ansible_facts.services['prometheus.service'] is not defined
  tags: ['never', 'bootstrap']

- import_tasks: configuration.yml
  tags: ['never', 'bootstrap', 'addnode']
