---
- import_tasks: install_binary.yml

- name: Install docker console script
  copy:
    src: docker_console.sh
    dest: /etc/profile.d/
    owner: root
    group: root

- name: Ensure docker startup directory exists
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory

- name: Configure Docker Startup Script
  template:
    src: startup.conf
    dest: /etc/systemd/system/docker.service.d/startup.conf

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
