---
- name: Install docker dependencies
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
    state: present
    update_cache: true

- name: Install docker repo
  command: yum-config-manager -y --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    warn: false

- name: Install Docker
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present

# https://access.redhat.com/solutions/98873
- name: Lock docker version
  command: yum versionlock docker-ce docker-ce-cli containerd.io
  args:
    warn: false
  when: lock_docker_version

- name: Ensure docker is running
  service:
    name: docker
    enabled: yes
    state: started

- name: Ensure docker startup directory exists
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory

- name: Configure Docker Startup Script
  template:
    src: startup.conf
    dest: /etc/systemd/system/docker.service.d/startup.conf

- name: reload systemd
  systemd: daemon_reload=yes

- name: restart docker
  service:
    name: docker
    state: restarted