---
- block:
    - name: install docker key
      ansible.builtin.get_url:
        url: "{{ docker_deb_key }}"
        dest: "{{ docker_deb_key_path }}"
    - name: add docker repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ docker_deb_key_path }} arch=amd64] {{ docker_deb_repo_url }}"
        state: present

- name: install packages
  apt:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
    state: latest
    update_cache: yes

# `apt-get upgrade` on these will cause all containers to restart.
- name: Lock docker version
  ansible.builtin.command: apt-mark hold docker-ce docker-ce-cli containerd.io
  when: lock_docker_version

- name: Ensure docker is running
  systemd:
    name: docker
    enabled: yes
    state: restarted
