---
- include_tasks: centos/install.yml
  when: ansible_distribution == 'CentOS'
- include_tasks: debian/install.yml
  when: ansible_distribution == 'Debian'


- name: Ensure docker is running
  service:
    name: docker
    enabled: yes
    state: started

- name: Ensure docker startup directory exists
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory

- name: Configure Docker Startup Script
  template:
    src: startup.conf
    dest: /etc/systemd/system/docker.service.d/startup.conf

- name: reload systemd
  systemd: daemon_reload=yes

- name: restart docker
  service:
    name: docker
    state: restarted
