---
- name: docker | exists?
  shell: command -v docker >/dev/null 2>&1
  register: docker_exists
  ignore_errors: yes
  no_log: True
  vars:
    ansible_ssh_pipelining: no

- include_tasks: install.yml
  when: docker_exists is failed

