---
- import_tasks: validate/ip_addresses.yml
- import_tasks: validate/preflight.yml
- import_tasks: debian/packages.yml
- import_tasks: validate/postcheck.yml

- name: Ensure localhost is defined
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: 'localhost'
    line: 127.0.0.1 localhost
    owner: root
    group: root
    mode: '0644'

- name: install tmux.conf
  get_url:
    url: "{{ tmux_url }}"
    dest: /root/.tmux.conf

- name: Set Motd
  template:
    src: motd.j2
    dest: /etc/motd

- import_tasks: sshd.yml

- name: setup chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

- import_tasks: validate/dns.yml

