---
- include_tasks: preflight.yml

- name: Load service state
  service_facts:

- include_tasks: centos7/packages.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: debian/packages.yml
  when: ansible_distribution == 'Debian'

- include_tasks: debian/setup.yml
  when: ansible_distribution == 'Debian'

- include_tasks: centos7/kernel.yml
  when: is_centos_7

- name: install tmux.conf
  get_url:
    url: "{{ tmux_url }}"
    dest: /root/.tmux.conf

- name: Add Public DNS
  lineinfile: path=/etc/resolv.conf create=yes line={{item}}
  with_items:
    - "nameserver 1.1.1.1"
    - "nameserver 8.8.8.8"
    - "nameserver 1.0.0.1"
    - "nameserver 8.8.4.4"
  when: overwrite_resolvconf

- name: Set Motd
  template:
    src: motd.j2
    dest: /etc/motd

- name: Check if docker console script exists
  stat:
    path: /etc/profile.d/docker_console.sh
  register: docker_console_exists

- name: Install docker console script
  copy:
    src: docker_console.sh
    dest: /etc/profile.d/
    owner: root
    group: root
  when: docker_console_exists.stat.exists == False

- include_tasks: sshd.yml

- include_tasks: computestacks.yml

- name: setup chronyd
  service:
    name: chronyd
    state: started
    enabled: yes
