---
- import_tasks: validate/ip_addresses.yml
- import_tasks: validate/preflight.yml
- import_tasks: debian/packages.yml
- import_tasks: validate/postcheck.yml
- import_tasks: debian/setup.yml

- name: install tmux.conf
  get_url:
    url: "{{ tmux_url }}"
    dest: /root/.tmux.conf

- name: Set Motd
  template:
    src: motd.j2
    dest: /etc/motd

- import_tasks: sshd.yml

- name: setup chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

- import_tasks: validate/dns.yml

