---
- name: Ensure SELinux is enabled
  fail:
    msg: SELinux is disabled
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_selinux == False or ansible_selinux.status == 'disabled'

- name: Ensure portal domain exists
  fail:
    msg: "'cs_portal_domain' is not defined"
  when: cs_portal_domain == ""

- name: Ensure registry domain exists
  fail:
    msg: "'cs_registry_domain' is not defined"
  when: cs_registry_domain == ""

- name: Ensure Floating IP exists
  fail:
    msg: "'floating_ip' is not defined"
  when: floating_ip == ""

- name: Ensure global region name defined
  fail:
    msg: "'global_region_name' is not defined"
  when: global_region_name == ""

- name: Ensure default app url is defined
  fail:
    msg: "'cs_app_url' is not defined"
  when: cs_app_url == ""

- name: Ensure correct linux variant
  fail:
    msg: "Invalid OS distribution. Only CentOS 7 and Debian 10 are supported."
  when:
    - ansible_distribution != "CentOS"
    - ansible_distribution != 'Debian'

- name: Ensure supported linux version (CentOS)
  fail:
    msg: "Invalid CentOS version. Only version 7 is supported"
  when: 
    - ansible_facts['distribution_major_version']|int < 7 or ansible_facts['distribution_major_version']|int > 7
    - ansible_distribution == 'CentOS'

- name: Ensure supported linux version (Debian)
  fail:
    msg: "Invalid Debian version. Only version 10 is supported"
  when: 
    - ansible_facts['distribution_major_version']|int == "10"
    - ansible_distribution == 'Debian'

- name: Ensure DigitalOcean token exists
  fail:
    msg: "DigitalOcean is selected, but missing platform_do_token"
  when:
    - "cloud_platform == 'digitalocean'"
    - "platform_do_token == ''"
