---
- name: check if root ssh key exists
  stat:
    path: /root/.ssh/id_ed25519
  register: root_ssh_key_exists

- name: generate root key
  openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    owner: root
    group: root
  when: root_ssh_key_exists.stat.exists == False

- name: Ensure SSH keys are installed
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/cs-portal
    - public_keys/kris

- file:
    path: /etc
    state: directory
    mode: g-w
  notify: restart ssh

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh