---
- name: ensure controller exists
  community.general.docker_container_info:
    name: portal
  register: portal_container

- name: Controller missing
  fail:
    msg: "Controller missing, try running: cstacks run."
  when: not portal_container.exists

- name: Controller offline
  fail:
    msg: "Controller offline, try running: docker start portal"
  when:
    - portal_container.exists
    - "portal_container.container['State']['Status'] != 'running'"

- name: Check controller connections
  shell: cstacks test
  vars:
    ansible_ssh_pipelining: no
