---
- name: ensure controller exists
  community.general.docker_container_info:
    name: portal
  register: portal_container

- name: attempt portal recovery
  shell: cstacks run >/dev/null 2>&1
  ignore_errors: yes
  no_log: True
  vars:
    ansible_ssh_pipelining: no
  when: not portal_container.exists

- name: recheck controller
  block:
    - name: attempt to start portal container
      community.general.docker_container:
        name: portal
        state: started
    - community.general.docker_container_info:
        name: portal
      register: portal_container_final
    - name: portal does not exist
      fail:
        msg: Failed to boot controller
      when: not portal_container_final.exists
    - name: portal not running
      fail:
        msg: Failed to boot controller
      when:
        - portal_container_final.exists
        - "portal_container.container['State']['Status'] != 'running'"
  when:
    - portal_container.exists
    - "portal_container.container['State']['Status'] != 'running'"

- name: Check controller connections
  shell: cstacks test
  vars:
    ansible_ssh_pipelining: no
