---
- include_tasks: common/cadvisor.yml
- include_tasks: common/docker.yml
- include_tasks: common/node_exporter.yml
- include_tasks: common/nginx.yml

- name: redis
  fail:
    msg: redis is not running
  when: 
    - ansible_distribution == 'CentOS' 
    - ansible_facts.services['redis.service']['state'] != 'running'

- name: redis
  fail:
    msg: redis is not running
  when: 
    - ansible_distribution == 'Debian' 
    - ansible_facts.services['redis-server.service']['state'] != 'running'

- name: postgres
  fail:
    msg: postgresql is not running
  when:
    - ansible_distribution == 'CentOS' 
    - ansible_facts.services['postgresql-13.service']['state'] != 'running'

- name: postgres
  fail:
    msg: postgresql is not running
  when:
    - ansible_distribution == 'Debian'
    - ansible_facts.services['postgresql@13-main.service']['state'] != 'running'
