---
- name: Remove conflicting packages
  package:
    name: ['ufw', 'ntp']
    state: absent

- name: Install base packages
  apt:
    name:
      - apparmor
      - openssl
      - vim
      - dnsutils
      - net-tools
      - gnupg2
      - pass
      - ca-certificates
      - traceroute
      - sysstat
      - chrony
      - curl
      - wget
      - tree
      - iptables
      - jq
      - whois
      - mosh
      - socat
      - python3-openssl
      - python3-docker
      - git
      - linux-headers-amd64
      - rsync
      - sudo
      - apt-transport-https
      - gnupg-agent
      - software-properties-common
      - man
    state: latest

- name: install nfs client tools
  apt:
    name: nfs-common
    state: latest
  when: "'nodes' in group_names or 'backup_server' in group_names"
