---
- name: Switch iptables to legacy mode
  block:
    - community.general.alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy
    - community.general.alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy
  when: "'nodes' in group_names"
