---
##
# Sources:
# * http://do.co/assign-ip -> https://gist.github.com/andrewsomething/75a1d6acd1155013fabd
# * https://www.digitalocean.com/community/tutorials/how-to-create-a-high-availability-setup-with-corosync-pacemaker-and-floating-ips-on-ubuntu-14-04
- name: install assign-ip script
  copy:
    src: digitalocean/assign-ip.sh
    dest: /usr/local/bin/assign-ip
    group: root
    owner: root
    mode: 0655

- file:
    path: /usr/lib/ocf/resource.d/digitalocean
    state: directory

# Source: https://gist.github.com/thisismitch/b4c91438e56bfe6b7bfb
- name: install digitalocean ocf resource agent
  copy:
    src: digitalocean/ocf.sh
    dest: /usr/lib/ocf/resource.d/digitalocean/floatip
    group: root
    owner: root
    mode: 0655

- name: Activate Floating IP
  block:
    - name: create vip resource
      command: "pcs resource create DO_VIP ocf:digitalocean:floatip floating_ip={{ floating_ip }} do_token={{ platform_do_token }}"
    - name: create VIP group
      command: pcs resource group add VIP DO_VIP
    - name: create vip without interface
      command: "pcs resource create FLOATINGIP ocf:heartbeat:IPaddr2 ip={{ floating_ip }} cidr_netmask={{ floating_ip_netmask | int }} --group VIP"
      when: floating_ip_interface == ''
    - name: create vip with interface
      command: "pcs resource create FLOATINGIP ocf:heartbeat:IPaddr2 ip={{ floating_ip }} cidr_netmask={{ floating_ip_netmask | int }} nic={{ floating_ip_interface }} --group VIP"
      when: floating_ip_interface != ''
  when: enable_floating_ip
  run_once: true
