---
- name: create vip without interface
  command: "pcs resource create VIP ocf:heartbeat:IPaddr2 ip={{ floating_ip }} cidr_netmask={{ floating_ip_netmask | int }}"
  when:
    - floating_ip_interface == ''
    - enable_floating_ip
  run_once: true

- name: create vip with interface
  command: "pcs resource create VIP ocf:heartbeat:IPaddr2 ip={{ floating_ip }} cidr_netmask={{ floating_ip_netmask | int }} nic={{ floating_ip_interface }}"
  when:
    - floating_ip_interface != ''
    - enable_floating_ip
  run_once: true
