---
- block:
    - import_tasks: install.yml
      when:
        - ansible_distribution == 'CentOS'
        - ansible_facts.services['postgresql-13.service'] is not defined
    - import_tasks: install.yml
      when:
        - ansible_distribution == 'Debian'
        - ansible_facts.services['postgresql.service'] is not defined
  tags: ['never', 'bootstrap']
