---
##
# NODES
# Settings set by inventory.yml
region_name: "dev"
availability_zone_name: "{{ region_name }}-a"

metrics_ip_address: ""

# optional changes
cadvisor_port: 8080
node_exporter_port: 9100
haproxy_stats_port: 81

##
# Local prom server

prometheus_image: "prom/prometheus"
prometheus_image_tag: "latest"
prometheus_full_image: "{{ prometheus_image }}:{{ prometheus_image_tag }}"

##
# Alerts
container_ignore_list: "alertmanager|consul|loki|loki-logs|cadvisor|portal|prometheus|grafana|calico-node|vault-bootstrap|nginx|haproxy|" # keep trailing pipe
container_cpu_limit: "95"
container_memory_limit: "92"
alert_manager_port: 9093
