---
- name: Download archive
  unarchive:
    src: "{{ agent_download_url }}"
    dest: /usr/local/src/
    remote_src: yes

# Should fail and kill ansible
# see: https://stackoverflow.com/questions/34340562/evaluating-return-code-in-ansible-conditional
- name: Verify integrity
  shell: |
    cd /usr/local/src && gpg --verify cs-agent.sig cs-agent
  args:
    warn: false

- name: Install agent binary
  copy:
    remote_src: true
    src: /usr/local/src/cs-agent
    dest: /usr/local/bin/cs-agent
    owner: root
    group: root
    mode: '0655'

- name: restart agent
  systemd:
    name: cs-agent
    state: restarted
  when: ansible_facts.services['cs-agent.service'] is defined

- name: clean downloads
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/usr/local/src/cs-agent"
    - "/usr/local/src/cs-agent.sig"
