---
- name: Load signing key
  copy:
    src: A8C477EE.asc
    dest: /root/.A8C477EE.asc

- name: Install gpg key
  shell: gpg --import /root/.A8C477EE.asc
  vars:
    ansible_ssh_pipelining: no

- name: ensure config directory exists
  file:
    path: "{{ agent_config_path }}"
    state: directory
    mode: '0740'

- import_tasks: setup_ssh_fs.yml
  when: backup_remote_protocol == 'ssh'

- import_tasks: install_binary.yml
- import_tasks: ssl_consul.yml
- import_tasks: ssl_docker.yml

- name: read consul token
  slurp:
    src: "/root/.consul.secret"
  register: consul_token_raw
  delegate_to: "{{ groups['nodes'][0] }}"
  run_once: true

- set_fact:
    consul_token: "{{ consul_token_raw.content | b64decode }}"
  run_once: true

- name: Install agent config
  template:
    src: agent.yml.j2
    dest: "{{ agent_config_path }}/agent.yml"
    mode: '0640'

- name: systemd conf file
  template:
    src: cs-agent.service.j2
    dest: /etc/systemd/system/cs-agent.service

- name: start agent
  systemd:
    name: cs-agent
    state: started
    enabled: yes
    daemon_reload: yes
