---
- name: ensure config directory exists
  file:
    path: "{{ agent_config_path }}"
    state: directory
    mode: '0740'

- import_tasks: setup_ssh_fs.yml

- import_tasks: ssl_consul.yml
- import_tasks: ssl_docker.yml

- name: read consul token
  slurp:
    src: "/root/.consul.secret"
  register: consul_token_raw
  delegate_to: "{{ groups['nodes'][0] }}"
  run_once: true

- set_fact:
    consul_token: "{{ consul_token_raw.content | b64decode }}"
  run_once: true

- name: Install agent config
  template:
    src: agent.yml.j2
    dest: "{{ agent_config_file_path }}"
    mode: '0640'

- name: pull image
  community.general.docker_image:
    name: "{{ agent_image }}"
    tag: "{{ agent_image_tag }}"
    source: pull

- name: systemd conf file
  template:
    src: cs-agent.service.j2
    dest: /etc/systemd/system/cs-agent.service

- name: start agent
  systemd:
    name: cs-agent
    state: started
    enabled: yes
    daemon_reload: yes
