---
- name: etcd_config | exists?
  shell: systemctl status etcd >/dev/null 2>&1
  register: etcd_exists
  ignore_errors: yes
  no_log: True
  vars:
    ansible_ssh_pipelining: no

- include_tasks: install.yml
  when: etcd_exists is failed
